[template]
src = "ssl_servers.conf.tmpl"
dest = "/etc/nginx/conf.d/ssl_servers.conf"
owner = "nginx"
mode = "0644"
keys = [
    "/ngx_entry/ssl_upstream",
    "/ngx_entry/ssl_servers",
]
check_cmd = "/usr/sbin/nginx -t"
reload_cmd = "/usr/sbin/service nginx reload"
