[template]
src = "servers.conf.tmpl"
dest = "/etc/nginx/conf.d/servers.conf"
owner = "nginx"
mode = "0644"
keys = [
    "/ngx_entry/upstream",
    "/ngx_entry/servers",
]
check_cmd = "/usr/sbin/nginx -t"
reload_cmd = "/usr/sbin/service nginx reload"
